title: AI Prompts for Business Immigration
description: A library of AI Prompts for Business Immigration
theme: just-the-docs

url: https://immigration-prompts.github.io

aux_links:
  "Submit a Prompt (Coming Soon)": https://github.com/immigration-prompts/immigration-prompts.github.io/issues

# aux_links:
#   "Submit via Google Form": https://forms.google.com/yourlink
#   "Submit via GitHub": https://github.com/immigration-prompts/immigration-prompts.github.io/issues/new/choose
